#
# Extra debloat list (only applied when ROM_DEBLOAT_LEVEL="ultra")
#
# - Add entries inside the specific partition containing that file (<PARTITION>_DEBLOAT+="")
# - DO NOT add the partition name at the start of any entry (eg. "/system/dpolicy_system")
# - DO NOT add a slash at the start of any entry (eg. "/dpolicy_system")
#

SYSTEM_DEBLOAT+="
system/app/AASAservice/AASAservice.apk
system/app/ARCore/ARCore.apk
system/app/AllShareAware/AllShareAware.apk
system/app/AllshareMediaShare/AllshareMediaShare.apk
system/app/BBCAgent/BBCAgent.apk
system/app/BGMProvider/BGMProvider.apk
system/app/BasicDreams/BasicDreams.apk
system/app/BixbyWakeup/BixbyWakeup.apk
system/app/BluetoothAgent/BluetoothAgent.apk
system/app/BluetoothMidiService/BluetoothMidiService.apk
system/app/BookmarkProvider/BookmarkProvider.apk
system/app/CameraExtensionsProxy/CameraExtensionsProxy.apk
system/app/CaptivePortalLoginGoogle/CaptivePortalLoginGoogle.apk
system/app/ClipboardEdge/ClipboardEdge.apk
system/app/CocktailQuickTool/CocktailQuickTool.apk
system/app/CompanionDeviceManager/CompanionDeviceManager.apk
system/app/ContainerService/ContainerService.apk
system/app/DAAgent/DAAgent.apk
system/app/DRParser/DRParser.apk
system/app/DsmsAPK/DsmsAPK.apk
system/app/EasterEgg/EasterEgg.apk
system/app/EasyOneHand3/EasyOneHand3.apk
system/app/EasymodeContactsWidget81/EasymodeContactsWidget81.apk
system/app/FactoryAirCommandManager/FactoryAirCommandManager.apk
system/app/FactoryCameraFB/FactoryCameraFB.apk
system/app/Foundation/Foundation.apk
system/app/GalaxyResourceUpdater/GalaxyResourceUpdater.apk
system/app/GearManagerStub/GearManagerStub.apk
system/app/GooglePrintRecommendationService/GooglePrintRecommendationService.apk
system/app/HMT/HMT.apk
system/app/HandwritingService/HandwritingService.apk
system/app/HiyaService/HiyaService.apk
system/app/HoneyBoard/HoneyBoard.apk
system/app/ImsSettings/ImsSettings.apk
system/app/LiveTranscribe/LiveTranscribe.apk
system/app/MdecService/MdecService.apk
system/app/MdxKitService/MdxKitService.apk
system/app/MhsAiService/MhsAiService.apk
system/app/MoccaMobile/MoccaMobile.apk
system/app/MotionPhoto/MotionPhoto.apk
system/app/MyDevice/MyDevice.apk
system/app/NfwLocationPrivacy/NfwLocationPrivacy.apk
system/app/OCRDataProvider/OCRDataProvider.apk
system/app/P2pAwareOverlay/P2pAwareOverlay.apk
system/app/PacProcessor/PacProcessor.apk
system/app/ParentalCare/ParentalCare.apk
system/app/PartnerBookmarksProvider/PartnerBookmarksProvider.apk
system/app/Personalization/Personalization.apk
system/app/PhotoTable/PhotoTable.apk
system/app/PrintSpooler/PrintSpooler.apk
system/app/PrivateAccessTokens/PrivateAccessTokens.apk
system/app/Roboto/Roboto.apk
system/app/SafetyInformation/SafetyInformation.apk
system/app/SamsungAiCore/SamsungAiCore.apk
system/app/SamsungOne/SamsungOne.apk
system/app/SamsungTTS/SamsungTTS.apk
system/app/SamsungTTSVoice_en_US_l03/SamsungTTSVoice_en_US_l03.apk
system/app/SetupWizardLegalProvider/SetupWizardLegalProvider.apk
system/app/ShortcutBackupService/ShortcutBackupService.apk
system/app/SimMobilityKit/SimMobilityKit.apk
system/app/SketchBook/SketchBook.apk
system/app/SmartCapture/SmartCapture.apk
system/app/SmartManager_v6_DeviceSecurity/SmartManager_v6_DeviceSecurity.apk
system/app/SmartMirroring/SmartMirroring.apk
system/app/SmartSwitchAgent/SmartSwitchAgent.apk
system/app/SmartTethering/SmartTethering.apk
system/app/StickerCenter/StickerCenter.apk
system/app/Stk/Stk.apk
system/app/Stk2/Stk2.apk
system/app/TEEgrisTuiService/TEEgrisTuiService.apk
system/app/TetheringAutomation/TetheringAutomation.apk
system/app/UnifiedWFC/UnifiedWFC.apk
system/app/VideoEditorLite_Dream_N/VideoEditorLite_Dream_N.apk
system/app/VisionIntelligence3.7/VisionIntelligence3.7.apk
system/app/VisualCloudCore/VisualCloudCore.apk
system/app/VoiceAccess/VoiceAccess.apk
system/app/WallpaperBackup/WallpaperBackup.apk
system/app/WallpaperMagician/WallpaperMagician.apk
system/app/WifiAiService/WifiAiService.apk
system/app/WlanTest/WlanTest.apk
system/priv-app/AdaptSound_V/AdaptSound_V.apk
system/priv-app/AudioMirroring/AudioMirroring.apk
system/priv-app/AutoDoodle/AutoDoodle.apk
system/priv-app/AvatarEmojiSticker/AvatarEmojiSticker.apk
system/priv-app/AvatarPicker/AvatarPicker.apk
system/priv-app/BackupRestoreConfirmation/BackupRestoreConfirmation.apk
system/priv-app/BadgeProvider_N/BadgeProvider_N.apk
system/priv-app/BeaconManager/BeaconManager.apk
system/priv-app/Bixby/Bixby.apk
system/priv-app/BixbyInterpreter/BixbyInterpreter.apk
system/priv-app/BixbyVisionFramework3.5/BixbyVisionFramework3.5.apk
system/priv-app/BuiltInPrintService/BuiltInPrintService.apk
system/priv-app/CIDManager/CIDManager.apk
system/priv-app/CMHProvider/CMHProvider.apk
system/priv-app/CSC/CSC.apk
system/priv-app/CallAssistant/CallAssistant.apk
system/priv-app/CallBGProvider/CallBGProvider.apk
system/priv-app/CallContentProvider/CallContentProvider.apk
system/priv-app/CallLogBackup/CallLogBackup.apk
system/priv-app/Crane/Crane.apk
system/priv-app/DeXonPC/DeXonPC.apk
system/priv-app/DesktopModeUiService/DesktopModeUiService.apk
system/priv-app/DesktopSystemUI/DesktopSystemUI.apk
system/priv-app/DeviceBasedServiceConsent/DeviceBasedServiceConsent.apk
system/priv-app/DeviceDiagnostics/DeviceDiagnostics.apk
system/priv-app/DeviceKeystring/DeviceKeystring.apk
system/priv-app/DeviceQualityAgent35/DeviceQualityAgent35.apk
system/priv-app/DigitalWellbeing/DigitalWellbeing.apk
system/priv-app/DynamicLockscreen/DynamicLockscreen.apk
system/priv-app/DynamicSystemInstallationService/DynamicSystemInstallationService.apk
system/priv-app/E2eeContactKeysProvider/E2eeContactKeysProvider.apk
system/priv-app/EarphoneTypeC/EarphoneTypeC.apk
system/priv-app/EasySetup/EasySetup.apk
system/priv-app/EmergencySOS/EmergencySOS.apk
system/priv-app/EpdgService/EpdgService.apk
system/priv-app/FacAtFunction/FacAtFunction.apk
system/priv-app/FaceService/FaceService.apk
system/priv-app/FactoryTestProvider/FactoryTestProvider.apk
system/priv-app/Fmm/Fmm.apk
system/priv-app/GalaxyApps_OPEN/GalaxyApps_OPEN.apk
system/priv-app/GalleryWidget/GalleryWidget.apk
system/priv-app/GameOptimizingService/GameOptimizingService.apk
system/priv-app/GameTools_Dream/GameTools_Dream.apk
system/priv-app/GpuWatchApp/GpuWatchApp.apk
system/priv-app/HWResourceShare/HWResourceShare.apk
system/priv-app/HashTagService/HashTagService.apk
system/priv-app/HealthServicePAR/HealthServicePAR.apk
system/priv-app/IAFDManagerService/IAFDManagerService.apk
system/priv-app/IPService/IPService.apk
system/priv-app/IntelligentDynamicFpsService/IntelligentDynamicFpsService.apk
system/priv-app/KLMSAgent/KLMSAgent.apk
system/priv-app/KnoxDesktopLauncher/KnoxDesktopLauncher.apk
system/priv-app/LedBackCoverAppBeyond/LedBackCoverAppBeyond.apk
system/priv-app/LedCoverService/LedCoverService.apk
system/priv-app/LinkToWindowsService/LinkToWindowsService.apk
system/priv-app/LiveEffectService/LiveEffectService.apk
system/priv-app/MCFDeviceSync/MCFDeviceSync.apk
system/priv-app/MFContents/MFContents.apk
system/priv-app/ManagedProvisioning/ManagedProvisioning.apk
system/priv-app/MediaSearch/MediaSearch.apk
system/priv-app/MmsService/MmsService.apk
system/priv-app/MobileWips/MobileWips.apk
system/priv-app/ModemServiceMode/ModemServiceMode.apk
system/priv-app/MultiControl/MultiControl.apk
system/priv-app/MultiSoundSetting/MultiSoundSetting.apk
system/priv-app/NSDSWebApp/NSDSWebApp.apk
system/priv-app/NetworkDiagnostic/NetworkDiagnostic.apk
system/priv-app/NfcNci/NfcNci.apk
system/priv-app/ONS/ONS.apk
system/priv-app/OfflineLanguageModel_stub/OfflineLanguageModel_stub.apk
system/priv-app/OmaCP/OmaCP.apk
system/priv-app/PeopleStripe/PeopleStripe.apk
system/priv-app/PhoneErrService/PhoneErrService.apk
system/priv-app/PhoneNumberService/PhoneNumberService.apk
system/priv-app/ProxyHandler/ProxyHandler.apk
system/priv-app/QMDService/QMDService.apk
system/priv-app/RubinVersion36/RubinVersion36.apk
system/priv-app/SCPMAgent/SCPMAgent.apk
system/priv-app/SDMConfig/SDMConfig.apk
system/priv-app/SHClient/SHClient.apk
system/priv-app/SVCAgent/SVCAgent.apk
system/priv-app/SamsungAccount/SamsungAccount.apk
system/priv-app/SamsungBilling/SamsungBilling.apk
system/priv-app/SamsungCloudClient/SamsungCloudClient.apk
system/priv-app/SamsungContacts/SamsungContacts.apk
system/priv-app/SamsungContactsProvider/SamsungContactsProvider.apk
system/priv-app/SamsungDialer/SamsungDialer.apk
system/priv-app/SamsungExperienceService/SamsungExperienceService.apk
system/priv-app/SamsungInCallUI/SamsungInCallUI.apk
system/priv-app/SamsungIntelliVoiceServices/SamsungIntelliVoiceServices.apk
system/priv-app/SamsungMagnifier3/SamsungMagnifier3.apk
system/priv-app/SamsungMessages/SamsungMessages.apk
system/priv-app/SamsungMultiConnectivity/SamsungMultiConnectivity.apk
system/priv-app/SamsungSmartSuggestions/SamsungSmartSuggestions.apk
system/priv-app/SecAppSeparation/SecAppSeparation.apk
system/priv-app/SecFactoryPhoneTest/SecFactoryPhoneTest.apk
system/priv-app/SecSetupWizard_Global/SecSetupWizard_Global.apk
system/priv-app/SecureFolder/SecureFolder.apk
system/priv-app/SemanticSearchCore/SemanticSearchCore.apk
system/priv-app/SendHelpMessage/SendHelpMessage.apk
system/priv-app/ShareLive/ShareLive.apk
system/priv-app/SharedStorageBackup/SharedStorageBackup.apk
system/priv-app/SingleTakeService/SingleTakeService.apk
system/priv-app/SmartCallProvider/SmartCallProvider.apk
system/priv-app/SmartEpdgTestApp/SmartEpdgTestApp.apk
system/priv-app/SmartSwitchAssistant/SmartSwitchAssistant.apk
system/priv-app/SmartThingsKit/SmartThingsKit.apk
system/priv-app/SmartTouchCall/SmartTouchCall.apk
system/priv-app/SohService/SohService.apk
system/priv-app/SpriteWallpaper/SpriteWallpaper.apk
system/priv-app/StoryService/StoryService.apk
system/priv-app/Tag/Tag.apk
system/priv-app/TalkbackSE/TalkbackSE.apk
system/priv-app/TaskEdgePanel_v3.2/TaskEdgePanel_v3.2.apk
system/priv-app/Telecom/Telecom.apk
system/priv-app/TelephonyUI/TelephonyUI.apk
system/priv-app/ThemeCenter/ThemeCenter.apk
system/priv-app/ThemeStore/ThemeStore.apk
system/priv-app/USBSettings/USBSettings.apk
system/priv-app/VexScanner/VexScanner.apk
system/priv-app/VisionModel-Stub/VisionModel-Stub.apk
system/priv-app/VolumeMonitorProvider_V/VolumeMonitorProvider_V.apk
system/priv-app/serviceModeApp_FB/serviceModeApp_FB.apk
system/priv-app/smartfaceservice/smartfaceservice.apk
system/priv-app/vexfwk_service/vexfwk_service.apk
"

PRODUCT_DEBLOAT+="
app/GoogleCalendarSyncAdapter/GoogleCalendarSyncAdapter.apk
app/GoogleLocationHistory/GoogleLocationHistory.apk
app/SpeechServicesByGoogle/SpeechServicesByGoogle.apk
app/WcmUrlsNetworkStackOverlay/WcmUrlsNetworkStackOverlay.apk
app/com.google.mainline.adservices/com.google.mainline.adservices.apk
app/com.google.mainline.telemetry/com.google.mainline.telemetry.apk
overlay/CompanionDeviceManager__phone__auto_generated_characteristics_rro.apk
overlay/FontNotoSerifSource/FontNotoSerifSourceOverlay.apk
overlay/GoogleHealthFitnessFrameworkOverlay.apk
overlay/NavigationBarMode3Button/NavigationBarMode3ButtonOverlay.apk
overlay/NotesRoleEnabled/NotesRoleEnabledOverlay.apk
overlay/SecTelephonyProvider__phone__auto_generated_characteristics_rro.apk
overlay/SettingsProvider__r12sxxx__auto_generated_rro_product.apk
overlay/TeleService__phone__auto_generated_characteristics_rro.apk
overlay/TeleService__r12sxxx__auto_generated_rro_product.apk
priv-app/AICore/AICore.apk
priv-app/AiWallpaper/AiWallpaper.apk
priv-app/AndroidAutoStub/AndroidAutoStub.apk
priv-app/AndroidSystemIntelligence/AndroidSystemIntelligence.apk
priv-app/CarrierWifi/CarrierWifi.apk
priv-app/ConfigUpdater/ConfigUpdater.apk
priv-app/FamilyLinkParentalControls/FamilyLinkParentalControls.apk
priv-app/GoogleOneTimeInitializer/GoogleOneTimeInitializer.apk
priv-app/GooglePartnerSetup/GooglePartnerSetup.apk
priv-app/HotwordEnrollmentOKGoogleExCORTEXM4/HotwordEnrollmentOKGoogleExCORTEXM4.apk
priv-app/HotwordEnrollmentXGoogleExCORTEXM4/HotwordEnrollmentXGoogleExCORTEXM4.apk
priv-app/PrivateComputeServices/PrivateComputeServices.apk
"

SYSTEM_EXT_DEBLOAT+="
app/ModemLogging/ModemLogging.apk
overlay/smartfaceservice_overlay.apk
priv-app/CarrierConfig/CarrierConfig.apk
priv-app/GoogleFeedback/GoogleFeedback.apk
priv-app/SetupWizard/SetupWizard.apk
priv-app/WallpaperCropper/WallpaperCropper.apk
"
