TMP_IMG_DIR="$1"
TMP_DIR="${TMP_DIR:-$OUT_DIR/tmp}"
TARGET_FIRMWARE_PATH="$(cut -d "/" -f 1 -s <<< "$TARGET_FIRMWARE")_$(cut -d "/" -f 2 -s <<< "$TARGET_FIRMWARE")"
TARGET_FIRMWARE_MODEL="$(cut -d "/" -f 1 -s <<< "$TARGET_FIRMWARE")"
TARGET_FIRMWARE_CSC="$(cut -d "/" -f 2 -s <<< "$TARGET_FIRMWARE")"
TARGET_FIRMWARE_MODEL_ALT="${TARGET_FIRMWARE_MODEL#SM-}"
PACK_DIR="${TARGET_AVB_IMAGE_PACK_DIR:-$OUT_DIR/target/$TARGET_CODENAME/signed_images}"
TARGET_ENABLE_SAMSUNG_SIGNING="${TARGET_ENABLE_SAMSUNG_SIGNING:-false}"
TARGET_SAMSUNG_SIGN_BOOTLOADER="${TARGET_SAMSUNG_SIGN_BOOTLOADER:-$TARGET_ENABLE_SAMSUNG_SIGNING}"
TARGET_SAMSUNG_SIGNED_BOOTLOADER_DIR="${TARGET_SAMSUNG_SIGNED_BOOTLOADER_DIR:-$OUT_DIR/target/$TARGET_CODENAME/signed_bootloader}"
mkdir -p "$TMP_DIR" || exit 1
STAGING_DIR="$(mktemp -d "$TMP_DIR/avb_sign.XXXXXX")" || exit 1
DEFAULT_CUSTOM_AVB_KEY_DIR="$SRC_DIR/security/avb"
DEFAULT_CUSTOM_AVB_KEY_NAME="creckerrom_avb"
DEFAULT_CUSTOM_AVB_KEY_PATH="$DEFAULT_CUSTOM_AVB_KEY_DIR/${DEFAULT_CUSTOM_AVB_KEY_NAME}_private.pem"
UPSTREAM_AVBTOOL_PATH="$SRC_DIR/external/android-tools/vendor/avb/avbtool.py"
AVB_METADATA_TOOL="$SRC_DIR/scripts/samsung_signing/avb_cli.py"
OPENSSL_COMPAT_DIR="$SRC_DIR/scripts/internal"
# Scratch lists are globals because each sourced module contributes to the same
# parse, signing, verification, and packaging pipeline.
DIRECT_DESCRIPTOR_IMAGES=""
ACTIVE_CHAIN_PARTITIONS=""
ORIGINAL_HASH_PARTITIONS=""
ORIGINAL_HASHTREE_PARTITIONS=""
ORIGINAL_CHAIN_PARTITIONS=""
ORIGINAL_VBMETA_PROPS=""
ORIGINAL_VBMETA_ALGORITHM=""
ORIGINAL_VBMETA_ROLLBACK_INDEX=""
ORIGINAL_VBMETA_ROLLBACK_INDEX_LOCATION=""
ORIGINAL_VBMETA_RELEASE_STRING=""
ORIGINAL_VBMETA_KERNEL_CMDLINE_COUNT=0
ORIGINAL_VBMETA_KERNEL_CMDLINES_FILE="$STAGING_DIR/original_vbmeta_kernel_cmdlines.tsv"
ORIGINAL_VBMETA_TRAILER_PATH=""
ORIGINAL_VBMETA_TRAILER_SIZE="0"
ORIGINAL_VBMETA_TRAILER_MARKER=""
ORIGINAL_VBMETA_SAMSUNG_PROPS=""
ORIGINAL_VBMETA_SAMSUNG_ALGORITHM=""
ORIGINAL_VBMETA_SAMSUNG_ROLLBACK_INDEX=""
ORIGINAL_VBMETA_SAMSUNG_ROLLBACK_INDEX_LOCATION=""
ORIGINAL_VBMETA_SAMSUNG_RELEASE_STRING=""
ORIGINAL_VBMETA_SAMSUNG_TRAILER_PATH=""
ORIGINAL_VBMETA_SAMSUNG_TRAILER_SIZE="0"
ORIGINAL_VBMETA_SAMSUNG_TRAILER_MARKER=""
VBMETA_SAMSUNG_DESCRIPTOR_PARTITIONS=""
HASH_PARTITIONS=""
HASHTREE_PARTITIONS=""
CHAIN_PARTITIONS=""
AVBTOOL_PATH=""
AVB_PYTHON_BIN=""
AVBTOOL_CMD=()
SIGNED_PARTITIONS=""
VBMETA_SIGN_KEY_PATH=""
VBMETA_SIGN_ALGORITHM=""
PARTITION_SIGN_KEY_PATH=""
PARTITION_SIGN_ALGORITHM=""
PARTITION_SIGN_HASH_ALGORITHM=""
PARTITION_SIGN_ROLLBACK_INDEX=""
PARTITION_SIGN_ROLLBACK_INDEX_LOCATION=""
PARTITION_SIGN_DO_NOT_USE_AB="false"
PARTITION_SIGN_EXTRA_ARGS=""
KEY_EXPORT_LABELS=""
KEY_EXPORT_REPORT="$STAGING_DIR/avb_keys.txt"
FIRMWARE_DESCRIPTOR_PACK_FILES=""
FIRMWARE_DESCRIPTOR_PACK_COMPONENTS=""
EXCLUDED_VBMETA_PARTITIONS="${TARGET_AVB_EXCLUDED_PARTITIONS-bootloader}"
REQUIRED_RE_SIGN_PARTITIONS="boot init_boot vendor_boot dtbo recovery"
INCLUDED_HASH_PARTITIONS=""
INCLUDED_HASHTREE_PARTITIONS=""
INCLUDED_CHAIN_PARTITIONS=""
# ]


PRINT_USAGE()
{
    echo "Usage: sign_avb_images <tmp_img_dir>" >&2
}

trap 'rm -rf "$STAGING_DIR"' EXIT INT

if [ "$#" -ne 1 ] || [ ! -d "$TMP_IMG_DIR" ]; then
    PRINT_USAGE
    exit 1
fi

INIT_DEFAULTS
SETUP_AVBTOOL
PARSE_ORIGINAL_VBMETA_LAYOUT
PARSE_ORIGINAL_VBMETA_SAMSUNG_LAYOUT
ADOPT_ORIGINAL_VBMETA_DEFAULTS
MERGE_LAYOUT
ASSERT_REQUIRED_RE_SIGN_COVERAGE
RESOLVE_TOPLEVEL_SIGNING_CONFIG
REGISTER_KEY_USAGE "vbmeta" "$VBMETA_SIGN_KEY_PATH" "$VBMETA_SIGN_ALGORITHM"

# Sign built images first so they can be reused as direct descriptors or chain
# targets when vbmeta is assembled below.
for PARTITION in $HASH_PARTITIONS $HASHTREE_PARTITIONS; do
    SIGN_BUILT_PARTITION "$PARTITION"
done

# Chain and external descriptor phases add metadata inputs for vbmeta without
# rebuilding every firmware component from source.
SIGN_CHAIN_PARTITIONS
SIGN_EXTERNAL_DESCRIPTOR_PARTITIONS
MAKE_TOPLEVEL_VBMETA
MAKE_VBMETA_SAMSUNG
VERIFY_SIGNED_AVB
CREATE_IMAGE_PACK
